server:
  port: 8080 #port? ?? ??? ??? ?? ??
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: tjfmstkf1@

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.38.239.60:3310/dongga_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: dongga_admin1
    password: tjfmstkf1@

  jpa:
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Seoul # 내장 톰캣 시간 설정

  main:
    time-zone: Asia/Seoul

  profiles:
    include: oauth

# 정적 파일 서버 재시작 안하고 바로 반영
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'

logging:
  level:
    org.hibernate.orm.jdbc.bind: info