server:
  port: 8080 #port? ?? ??? ??? ?? ??

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 12345678

  jpa:
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  profiles:
    include: oauth